name: brain_game
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^2.3.1
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  intl: ^0.17.0
  string_stats: ^0.1.0
  flutter_staggered_grid_view: ^0.4.1
  share: ^2.0.4
  lottie: ^1.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/